In [33]:
import numpy as np
import pandas as pd

In [34]:
df = pd.read_csv("data.csv")

In [35]:
df.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [36]:
df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [37]:
print("The datatypes of the columns are:\n",df.dtypes)

The datatypes of the columns are:
 Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [38]:
print("Statistical Data: ")
df.describe()

Statistical Data:

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [39]:
print("These are the missing values inside a column: ")
df.isnull().sum()

These are the missing values inside a column:

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [40]:
print("The mean value of the sales column can be calculated as: ",df['Sales'].mean())

The mean value of the sales column can be calculated as:  557.1304347826087

In [41]:
print("Filling missing values with the help of the mean of the column")
df["Sales_filled"] = df['Sales'].fillna(round(df['Sales'].mean(),2))
df

Filling missing values with the help of the mean of the column

          Date Category  Value   Product  Sales Region  Sales_filled
0   2023-01-01        A   28.0  Product1  754.0   East        754.00
1   2023-01-02        B   39.0  Product3  110.0  North        110.00
2   2023-01-03        C   32.0  Product2  398.0   East        398.00
3   2023-01-04        B    8.0  Product1  522.0   East        522.00
4   2023-01-05        B   26.0  Product3  869.0  North        869.00
5   2023-01-06        B   54.0  Product3  192.0   West        192.00
6   2023-01-07        A   16.0  Product1  936.0   East        936.00
7   2023-01-08        C   89.0  Product1  488.0   West        488.00
8   2023-01-09        C   37.0  Product3  772.0   West        772.00
9   2023-01-10        A   22.0  Product2  834.0   West        834.00
10  2023-01-11        B    7.0  Product1  842.0  North        842.00
11  2023-01-12        B   60.0  Product2    NaN   West        557.13
12  2023-01-13        A   70.0  Product3  628.0  South        628.00
13  2023-01-14        A   69.0  Product1  423.0   East        423.00
14  2023-01-15        A   47.0  Product2  893.0   West        893.00
15  2023-01-16        C    NaN  Product1  895.0  North        895.00
16  2023-01-17        C   93.0  Product2  511.0  South        511.00
17  2023-01-18        C    NaN  Product1  108.0   West        108.00
18  2023-01-19        A   31.0  Product2  578.0   West        578.00
19  2023-01-20        A   59.0  Product1  736.0   East        736.00
20  2023-01-21        C   82.0  Product3  606.0  South        606.00
21  2023-01-22        C   37.0  Product2  992.0  South        992.00
22  2023-01-23        B   62.0  Product3  942.0  North        942.00
23  2023-01-24        C   92.0  Product2  342.0   West        342.00
24  2023-01-25        A   24.0  Product2  458.0   East        458.00
25  2023-01-26        C   95.0  Product1  584.0   West        584.00
26  2023-01-27        C   71.0  Product2  619.0  North        619.00
27  2023-01-28        C   56.0  Product2  224.0  North        224.00
28  2023-01-29        B    NaN  Product3  617.0  North        617.00
29  2023-01-30        C   51.0  Product2  737.0  South        737.00
30  2023-01-31        B   50.0  Product3  735.0   West        735.00
31  2023-02-01        A   17.0  Product2  189.0   West        189.00
32  2023-02-02        B   63.0  Product3  338.0  South        338.00
33  2023-02-03        C   27.0  Product3    NaN   East        557.13
34  2023-02-04        C   70.0  Product3  669.0   West        669.00
35  2023-02-05        B   60.0  Product2    NaN   West        557.13
36  2023-02-06        C   36.0  Product3  177.0   East        177.00
37  2023-02-07        C    2.0  Product1    NaN  North        557.13
38  2023-02-08        C   94.0  Product1  408.0  South        408.00
39  2023-02-09        A   62.0  Product1  155.0   West        155.00
40  2023-02-10        B   15.0  Product1  578.0   East        578.00
41  2023-02-11        C   97.0  Product1  256.0   East        256.00
42  2023-02-12        A   93.0  Product3  164.0   West        164.00
43  2023-02-13        A   43.0  Product3  949.0   East        949.00
44  2023-02-14        A   96.0  Product3  830.0   East        830.00
45  2023-02-15        B   99.0  Product2  599.0   West        599.00
46  2023-02-16        B    6.0  Product1  938.0  South        938.00
47  2023-02-17        B   69.0  Product3  143.0   West        143.00
48  2023-02-18        C   65.0  Product3  182.0  North        182.00
49  2023-02-19        C   11.0  Product3  708.0  North        708.00

In [42]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_filled    float64
dtype: object

### EDA

In [43]:
print("Renaming column names")
df = df.rename(columns={'Date':'Sales_Date','Product':'Product_name'})
df.head()

Renaming column names

   Sales_Date Category  Value Product_name  Sales Region  Sales_filled
0  2023-01-01        A   28.0     Product1  754.0   East         754.0
1  2023-01-02        B   39.0     Product3  110.0  North         110.0
2  2023-01-03        C   32.0     Product2  398.0   East         398.0
3  2023-01-04        B    8.0     Product1  522.0   East         522.0
4  2023-01-05        B   26.0     Product3  869.0  North         869.0

In [44]:
df.isnull().sum()

Sales_Date      0
Category        0
Value           3
Product_name    0
Sales           4
Region          0
Sales_filled    0
dtype: int64

In [45]:
print("Use case of lambda function: ")
df['Increased_Value_twice'] = df['Value'].apply(lambda x:x*2)
df.head()

Use case of lambda function:

,Sales_Date,Category,Value,Product_name,Sales,Region,Sales_filled,Increased_Value_twice
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,52.0

In [47]:
df.isnull().sum()

Sales_Date               0
Category                 0
Value                    3
Product_name             0
Sales                    4
Region                   0
Sales_filled             0
Increased_Value_twice    3
dtype: int64

### Data Aggregations and Grouping

In [49]:
grouped_mean = df.groupby('Product_name')['Value'].mean()
print(grouped_mean)

Product_name
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [52]:
sales_based_on_region = df.groupby('Region')['Sales'].sum()
sales_based_on_region

Region
East     7017.0
North    6008.0
South    5158.0
West     7445.0
Name: Sales, dtype: float64

In [54]:
print("Aggregations: ")
grouped_agg = df.groupby('Region')['Value'].agg(['mean','sum','count'])
grouped_agg

Aggregations:

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

### Merging and joing data frames

In [61]:
df1 = pd.DataFrame({'Key' :['A','B','C'],'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key' :['A','B','D'],'Value2':[4,5,6]})
print(df1)
print(df2)

  Key  Value1
0   A       1
1   B       2
2   C       3
  Key  Value2
0   A       4
1   B       5
2   D       6

In [62]:
print("Merging dataframes based on the 'Key columns'")
pd.merge(df1,df2,on='Key',how='inner')

Merging dataframes based on the 'Key columns'

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [63]:
pd.merge(df1,df2,on='Key',how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0