In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv('train.csv',nrows=10000)

In [5]:
df.head()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

### Step 1 : make splits

In [8]:
x = df.drop('TARGET',axis=1)

In [10]:
y = df['TARGET']

In [12]:
x.head()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016

In [14]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: TARGET, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split

In [20]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [23]:
x_train.shape

(7000, 370)

In [25]:
x_test.shape

(3000, 370)

In [36]:
def correlation(dataset, threshold):
    col_corr = set()  # Set of all the names of correlated columns
    corr_matrix = dataset.corr()
    for i in range(len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i, j]) > threshold:  # we are interested in absolute coeff value
                colname = corr_matrix.columns[i]  # getting the name of column
                col_corr.add(colname)

    return col_corr
# “We use absolute correlation because both strong positive and strong negative correlations indicate redundancy between features.”

In [45]:
correlated_features = correlation(x_train,0.85)

In [46]:
print(len(correlated_features))

183

In [49]:
x_train.drop(correlated_features,axis=1)
x_test.drop(correlated_features,axis=1)

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var40_comer_ult1,imp_op_var40_efect_ult1,imp_op_var41_efect_ult1,imp_op_var41_efect_ult3,imp_sal_var16_ult1,...,saldo_medio_var13_largo_hace3,saldo_medio_var13_medio_hace2,saldo_medio_var13_medio_hace3,saldo_medio_var13_medio_ult1,saldo_medio_var13_medio_ult3,saldo_medio_var17_hace2,saldo_medio_var17_hace3,saldo_medio_var29_hace2,saldo_medio_var29_hace3,var38
9394,18882,2,23,0.0,0.00,0.0,0,0.0,0.0,0,...,0.0,0,0,0,0,0.0,0.0,0.0,0,75170.310000
898,1778,2,79,0.0,0.00,0.0,0,0.0,0.0,0,...,0.0,0,0,0,0,0.0,0.0,0.0,0,57855.510000
2398,4806,2,38,0.0,0.00,0.0,0,0.0,0.0,0,...,0.0,0,0,0,0,0.0,0.0,0.0,0,117310.979016
5906,11854,2,48,0.0,0.00,0.0,0,0.0,0.0,0,...,0.0,0,0,0,0,0.0,0.0,0.0,0,50659.230000
2343,4697,2,23,0.0,0.00,0.0,0,0.0,0.0,0,...,0.0,0,0,0,0,0.0,0.0,0.0,0,43843.320000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4004,8026,2,28,0.0,237.45,0.0,0,300.0,300.0,0,...,0.0,0,0,0,0,0.0,0.0,0.0,0,103622.310000
7375,14795,2,23,0.0,0.00,0.0,0,0.0,0.0,0,...,0.0,0,0,0,0,0.0,0.0,0.0,0,51898.800000
9307,18726,2,25,0.0,0.00,0.0,0,0.0,0.0,0,...,0.0,0,0,0,0,0.0,0.0,0.0,0,99251.790000
8394,16923,2,50,0.0,0.00,0.0,0,0.0,0.0,0,...,0.0,0,0,0,0,0.0,0.0,0.0,0,117310.979016
5233,10481,2,44,0.0,0.00,0.0,0,0.0,0.0,0,...,0.0,0,0,0,0,0.0,0.0,0.0,0,100466.730000