In [1]:
import seaborn as sns
import numpy as np
import pandas as pd

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.shape

(891, 15)

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
df = df[['sex','embarked','alone','pclass','survived']]

In [6]:
df.head()

      sex embarked  alone  pclass  survived
0    male        S  False       3         0
1  female        C  False       1         1
2  female        S   True       3         1
3  female        S  False       1         1
4    male        S   True       3         0

# Before applying Chi-Square test we need to apply label encoding

In [8]:
# sex column
df['sex'] = np.where(df['sex']=='male',1,0)

In [9]:
df.head()

   sex embarked  alone  pclass  survived
0    1        S  False       3         0
1    0        C  False       1         1
2    0        S   True       3         1
3    0        S  False       1         1
4    1        S   True       3         0

In [10]:
# embarked column
df['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [11]:
df['embarked'] = df['embarked'].map({'S':0,'C':1,'Q':2,np.nan:3})

In [12]:
df.head()

   sex  embarked  alone  pclass  survived
0    1         0  False       3         0
1    0         1  False       1         1
2    0         0   True       3         1
3    0         0  False       1         1
4    1         0   True       3         0

In [25]:
df['embarked'].unique()

array([0, 1, 2, 3], dtype=int64)

In [27]:
# now alone column
df['alone'] = np.where(df['alone']==True,1,0)

In [29]:
df.head()

   sex  embarked  alone  pclass  survived
0    1         0      0       3         0
1    0         1      0       1         1
2    0         0      1       3         1
3    0         0      0       1         1
4    1         0      1       3         0

# Now also a train test split in order to avoid overfitting

In [32]:
x = df.drop('survived',axis=1)
y = df['survived']

In [36]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [38]:
x_train.shape

(623, 4)

In [40]:
x_test.shape

(268, 4)

In [42]:
x_train.head()

     sex  embarked  alone  pclass
857    1         0      1       1
52     0         1      0       1
386    1         0      0       3
124    1         0      0       1
578    0         1      0       3

In [44]:
from sklearn.feature_selection import chi2

## Note : more the value of fscore more the important the feature is , lesser the pvalue more imp the feature

In [47]:
f_values , p_values = chi2(x_train,y_train)

In [49]:
f_values

array([63.55447864, 11.83961845,  9.03328564, 21.61080949])

In [51]:
p_values

array([1.55992554e-15, 5.79837058e-04, 2.65107556e-03, 3.33964360e-06])

In [53]:
p_values = pd.Series(p_values)

In [55]:
p_values.index=x_train.columns

In [67]:
p_values.sort_values(ascending=True)

sex         1.559926e-15
pclass      3.339644e-06
embarked    5.798371e-04
alone       2.651076e-03
dtype: float64

# Observation : sex column was the imp feature as in titanic movie also most of the women survived by transporting them through small boats and most **MEN** died