# Technique 1 - Removing Constant Values

In [2]:
import numpy as np
import pandas as pd

In [6]:
data = pd.DataFrame({
    "A": [1, 2, 4, 1, 2, 4],
    "B": [4, 5, 6, 7, 8, 9],
    "C": [0, 0, 0, 0, 0, 0],
    "D": [1, 1, 1, 1, 1, 1]
})

In [10]:
data

   A  B  C  D
0  1  4  0  1
1  2  5  0  1
2  4  6  0  1
3  1  7  0  1
4  2  8  0  1
5  4  9  0  1

### We will use the concept of **Variance Thresholding** where what happens is that we remove the columns according the variance threshold value if variance threshold value is 0 ie that colm will have a same value

In [13]:
from sklearn.feature_selection import VarianceThreshold

In [15]:
vt = VarianceThreshold(threshold=0)

In [17]:
vt.fit(data)

VarianceThreshold(threshold=0)

In [58]:
sum(vt.get_support())

284

In [34]:
const_colms = [col for col in data.columns if col not in data.columns[vt.get_support()]]

In [36]:
for useless_feature in const_colms:
    print(useless_feature)

C
D

In [40]:
data = data.drop(const_colms,axis=1)
data

   A  B
0  1  4
1  2  5
2  4  6
3  1  7
4  2  8
5  4  9

In [48]:
df = pd.read_csv('train.csv',nrows=10000)

In [50]:
df.head()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [52]:
X = df.drop(labels=['TARGET'],axis=1)
y = df['TARGET']

In [54]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.3,random_state=0)
X_train.shape , X_test.shape

((7000, 370), (3000, 370))

In [56]:
vt = VarianceThreshold(0)
vt.fit(X_train) # remember to fit on x train only on x test we perform transform

VarianceThreshold(threshold=0)

In [68]:
tot_cols = len(df.columns)
good_cols = sum(vt.get_support())

In [70]:
print(f"Good features are : {good_cols} and constant or bad features are : {tot_cols - good_cols}")

Good features are : 284 and constant or bad features are : 87

In [80]:
bad_cols = [col for col in X_train.columns if col not in X_train.columns[vt.get_support()]]

In [82]:
len(bad_cols)

86

In [84]:
for bad_col in bad_cols:
    print(bad_col)

ind_var2_0
ind_var2
ind_var13_medio_0
ind_var13_medio
ind_var18_0
ind_var18
ind_var27_0
ind_var28_0
ind_var28
ind_var27
ind_var34_0
ind_var34
ind_var41
ind_var46_0
ind_var46
num_var13_medio_0
num_var13_medio
num_var18_0
num_var18
num_var27_0
num_var28_0
num_var28
num_var27
num_var34_0
num_var34
num_var41
num_var46_0
num_var46
saldo_var13_medio
saldo_var18
saldo_var28
saldo_var27
saldo_var34
saldo_var41
saldo_var46
delta_imp_amort_var18_1y3
delta_imp_amort_var34_1y3
delta_imp_reemb_var17_1y3
delta_imp_reemb_var33_1y3
delta_imp_trasp_var17_out_1y3
delta_imp_trasp_var33_out_1y3
delta_num_reemb_var17_1y3
delta_num_reemb_var33_1y3
delta_num_trasp_var17_out_1y3
delta_num_trasp_var33_out_1y3
imp_amort_var18_hace3
imp_amort_var18_ult1
imp_amort_var34_hace3
imp_amort_var34_ult1
imp_var7_emit_ult1
imp_reemb_var13_hace3
imp_reemb_var17_hace3
imp_reemb_var17_ult1
imp_reemb_var33_hace3
imp_reemb_var33_ult1
imp_trasp_var17_in_hace3
imp_trasp_var17_out_hace3
imp_trasp_var17_out_ult1
imp_trasp_var33_in_hace3
imp_trasp_var33_out_hace3
imp_trasp_var33_out_ult1
imp_venta_var44_hace3
ind_var7_emit_ult1
num_var2_0_ult1
num_var2_ult1
num_var7_emit_ult1
num_meses_var13_medio_ult3
num_reemb_var13_hace3
num_reemb_var17_hace3
num_reemb_var17_ult1
num_reemb_var33_hace3
num_reemb_var33_ult1
num_trasp_var17_in_hace3
num_trasp_var17_out_hace3
num_trasp_var17_out_ult1
num_trasp_var33_in_hace3
num_trasp_var33_out_hace3
num_trasp_var33_out_ult1
num_venta_var44_hace3
saldo_var2_ult1
saldo_medio_var13_medio_hace2
saldo_medio_var13_medio_hace3
saldo_medio_var13_medio_ult1
saldo_medio_var13_medio_ult3
saldo_medio_var29_hace2
saldo_medio_var29_hace3

# Final step to drop columns

In [87]:
X_train = X_train.drop(bad_cols,axis=1)

In [89]:
len(X_train.columns)

284